# Generated by Django 4.1.7 on 2023-03-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventplace',
            name='availabililty',
            field=models.BooleanField(default=True),
        ),
    ]
