# Generated by Django 4.1.7 on 2023-03-11 08:20

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0002_eventplace_availabililty'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventplace',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, default=None, editable=False, null=True, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='eventplace',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='venues/'),
        ),
        migrations.CreateModel(
            name='CreatEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.TextField(blank=True, null=True)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('TicketPrice', models.PositiveIntegerField(blank=True, null=True)),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name', unique=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='event/')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventApp.eventplace')),
            ],
        ),
    ]
