# Generated by Django 4.1.7 on 2023-03-11 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0003_eventplace_slug_alter_eventplace_img_createvent'),
    ]

    operations = [
        migrations.AddField(
            model_name='createvent',
            name='eveManager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
