# Generated by Django 4.1.7 on 2023-03-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0004_createvent_evemanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='createvent',
            name='eveTyp',
            field=models.CharField(blank=True, choices=[('WeddingAnniversary', 'Wedding Anniversary'), ('BirthDay Party', 'BirthDay Party'), ('Conference', 'Conference'), ('CelebrationParty', 'Celebration Party')], max_length=50, null=True),
        ),
    ]
