# Generated by Django 4.1.7 on 2023-03-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0006_venues_alter_createvent_venue_delete_eventplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='createvent',
            name='nGuest',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
