# Generated by Django 4.1.7 on 2023-03-12 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0007_createvent_nguest'),
    ]

    operations = [
        migrations.AddField(
            model_name='createvent',
            name='endTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='createvent',
            name='startTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='createvent',
            name='endDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='createvent',
            name='startDate',
            field=models.DateField(),
        ),
    ]
