# Generated by Django 4.1.7 on 2023-03-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0009_createvent_tbkngprice_venues_mobno'),
    ]

    operations = [
        migrations.AddField(
            model_name='venues',
            name='mincpcty',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
