# Generated by Django 4.1.7 on 2023-03-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0010_venues_mincpcty'),
    ]

    operations = [
        migrations.AddField(
            model_name='createvent',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
