# Generated by Django 4.1.7 on 2023-03-13 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import eventApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0011_createvent_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rcptNo', models.CharField(default=eventApp.models.Receipt.create_new_ref_number, max_length=10)),
                ('rcptFor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
