# Generated by Django 4.1.7 on 2023-03-13 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0012_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventApp.createvent'),
        ),
    ]
