# Generated by Django 4.1.7 on 2023-03-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0013_receipt_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
