# Generated by Django 4.1.7 on 2023-03-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0014_receipt_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='createvent',
            name='payDone',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
