# Generated by Django 4.1.7 on 2023-03-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0015_createvent_paydone'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='rcptDate',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
