# Generated by Django 4.1.7 on 2023-03-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0018_venues_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='is_nUser',
            field=models.BooleanField(default=False),
        ),
    ]
