# Generated by Django 4.1.7 on 2023-03-19 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0022_msgs_delete_messages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Msgs',
        ),
    ]
