# Generated by Django 4.1.7 on 2023-03-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0024_msgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_emailVerified',
            field=models.BooleanField(default=False),
        ),
    ]
